<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title><?php echo $this->pageTitle; ?></title>
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/animate-css/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/assets/layout.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="text/javascript" src="/js/assets/bundle.min.js"></script>
    <script>
        var ax = new AjaxConnection();
        var ax2 = new AjaxConnection();
        ax.ajax(
            {
                'url': '/user/user/register',
                'data' : {
                    'username' : 'usertest1',
                    'password' : 'adfasdf123123',
                    'email'    : 'test@chilimatic.com'
                }
            }
        );
/*
        ax2.ajax(
            {
                'url': '/user/user/login',
                'data' : {
                    'username' : 'usertest1',
                    'password' : 'adfasdf123123'
                }
            }
        )
        */
    </script>
</head>
<body>
    <?php
        $fragment = new \chilimatic\lib\view\PHtml();
        if (isset($this->user)) {
            $fragment->user = $this->user;
        }
        echo $fragment->render(__DIR__ . '/fragment/navbar.phtml');
    ?>

    <div class="alert alert-info">
        <button id="new-card" type="button" class="btn btn-default" aria-label="left Align">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add New Card
        </button>
    </div>
    <div class="navabar-login">
        <?php if (!isset($this->user)): ?>
            <div class="form-signin">
                <input type="text" value="" placeholder="username" id="username" />
                <input type="text" value="" placeholder="password" id="password" />
                <button class="btn btn-lg" type="submit">Sign in</button>
            </div>
        <?php endif; ?>
    </div>
    <div class="container-fluid">
        <div class="swim-lane row">
            <div class="col-sm-4">
                <h2>New</h2>
            </div>
            <div class="col-sm-4">
                <h2>In Progress</h2>
            </div>
            <div class="col-sm-4">
                <h2>Done</h2>
            </div>
        </div>
        <div class="row droprow">
            <div id="new-col" class="col-sm-4 dropzone new"></div>
            <div class="col-sm-4 dropzone in-progress"></div>
            <div class="col-sm-4 dropzone done"></div>
        </div>
    </div>

</body>
</html>