<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title><?php echo $this->pageTitle; ?></title>
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/animate-css/animate.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="text/javascript" src="/js/lib/draganddrop.js"></script>
    <script type="text/javascript">

        document.addEventListener('DOMContentLoaded', function()
        {
            DragAndDrop.addDraggable(
                document.getElementsByClassName('card'),
                {
                    'dragstart'   : {
                        name: 'dragstart',
                        callback: function (e)
                        {
                            e.dataTransfer.effectAllowed = 'move';
                            elementDragged = this;
                            console.log('start');
                        }
                    },
                    'dragend'     : {
                        name: 'dragend',
                        callback: function (e)
                        {
                            console.log('end');
                            elementDragged = null;
                        }
                    },
                    'drag'        : {
                        callback: function(e)
                        {
                            console.log('drag');
                        }
                    }
                }
            );


            DragAndDrop.addDropZone('.dropzone', {
                drop : {
                    name : 'drop',
                    preventDefault: true,
                    callback : function(e)
                    {
                        elementDragged.parentNode.removeChild(elementDragged);
                        this.appendChild(elementDragged);
                        this.classList.remove('active');
                    }
                },
                dragover : {
                    preventDefault: true,
                    callback : function(e)
                    {
                        return false;
                    }
                },
                dragenter : {
                    name : 'dragenter',
                    callback : function(e)
                    {
                        this.classList.add('active');
                    }
                },
                dragleave : {
                    name : 'dragleave',
                    callback : function(e)
                    {
                        this.classList.remove('active');
                    }
                }
            });
        });



    </script>
    <style>
        .active {
            opacity: 0.8 !important;
        }

        .card {
            padding: 5px;
            cursor: pointer;
            z-index: 9999;
            display: inline-block;
            max-width: 250px;
            border: 1px solid #d3d3d3;
            background-color: #fff;
            border-radius: 5px;
            margin: 8px;
        }

        .row.droprow {
            display: flex;
            min-height: 200px;
            width: 100%;
        }
        .col-sm-4 {
            padding: 5px;
        }

        .col-sm-4.new {
            background-color: #c1fac3;
        }

        .col-sm-4.in-progress {
            background-color: #e5fab5;
        }

        .col-sm-4.done {
            background-color: #e5fab5;
        }

    </style>
</head>
<body>
    <?php
        $fragment = new \chilimatic\lib\view\PHtml();
        echo $fragment->render(__DIR__ . '/fragment/navbar.phtml');
    ?>

    <div class="alert alert-info">
        <button type="button" class="btn btn-default" aria-label="left Align">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add New Card
        </button>
    </div>
    <div class="card" draggable="true" style="background-color: #aaa">

    </div>
<!-- not working template
    <div class="card" draggable="true">
        <h4>I Want to do stuff</h4>
        <div>
            this is some text inside of it
            <ul>
                <li>with</li>
                <li>a</li>
                <li>list</li>
            </ul>
        </div>
    </div>
    -->
<!-- working template
    <a class="card" draggable="true">
        <h4>I Want to do stuff</h4>
        <div>
            this is some text inside of it
            <ul>
                <li>with</li>
                <li>a</li>
                <li>list</li>
            </ul>
        </div>
    </a>
-->

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <h2>New</h2>
            </div>
            <div class="col-sm-4">
                <h2>In Progress</h2>
            </div>
            <div class="col-sm-4">
                <h2>Done</h2>
            </div>
        </div>
        <div class="row droprow">
            <div class="col-sm-4 dropzone new"></div>
            <div class="col-sm-4 dropzone in-progress"></div>
            <div class="col-sm-4 dropzone done"></div>
        </div>
    </div>

</body>
</html>